# Generated by Django 5.1.6 on 2025-03-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_plan_alter_member_firstname_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
