# Generated by Django 5.1.6 on 2025-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='documento',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
