# Generated by Django 5.1.6 on 2025-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
